# config-maps.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sb-configs
  namespace: monitoring-labs
data:
  database.host: postgresql-ha-1727253526-pgpool.database-systems.svc.cluster.local
  database.port: "5432"
  database.name: spring_boot_monitoring_lab
  database.schema: monitoring_lab
  swagger.ui.path: /swagger-ui.html
  swagger.api.path: /api-docs

---
# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sb-secrets
  namespace: monitoring-labs
data:
  database.username: cG9zdGdyZXM=
  database.password: cG9zdGdyZXNzbWt6


