# config-maps.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sb-configs
  namespace: monitoring-labs
data:
  database.host: 127.0.0.1
  database.port: "5432"
  database.name: spring_boot_monitoring_lab
  database.schema: monitoring_lab
  swagger.ui.path: /swagger-ui.html
  swagger.api.path: /api-docs

---
# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sb-secrets
  namespace: monitoring-labs
data:
  database.username: cG9zdGdyZXM=
  database.password: c3ByaW5nLWJvb3QtbW9uaXRvcmluZy1sYWItcG9zdGdyZXM=


