apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-config
  namespace: observability
data:
  otel-agent-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      otlp:
        endpoint: "http://otel-collector.default.svc.cluster.local:4317"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
  database.host: 127.0.0.1
  database.port: "5432"
  database.name: spring_boot_monitoring_lab
  database.schema: monitoring_lab
  swagger.ui.path: /swagger-ui.html
  swagger.api.path: /api-docs



---
# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: otel-agent-secrets
  namespace: observability
data:
  database.username: cG9zdGdyZXM=
  database.password: c3ByaW5nLWJvb3QtbW9uaXRvcmluZy1sYWItcG9zdGdyZXM=


