# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-monitoring-lab
  labels:
    app: spring-boot-monitoring-lab
  namespace: monitoring-labs
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: spring-boot-monitoring-lab
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app: spring-boot-monitoring-lab
    spec:
      serviceAccountName: spring-lab-application-ksa
      # volumes:
      #   - name: service-account-secret
      #     secret:
      #       secretName: gsa-secret
      containers:
        - name: spring-boot-monitoring-lab
          image: samuikazeforwork/spring-boot-monitoring-lab:v18
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: sb-configs
                  key: database.host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: sb-configs
                  key: database.port
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: sb-configs
                  key: database.name
            - name: SCHEMA_NAME
              valueFrom:
                configMapKeyRef:
                  name: sb-configs
                  key: database.schema
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sb-secrets
                  key: database.username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sb-secrets
                  key: database.password
            - name: SWAGGER_UI_PATH
              valueFrom:
                configMapKeyRef:
                  name: sb-configs
                  key: swagger.ui.path
            - name: SWAGGER_API_PATH
              valueFrom:
                configMapKeyRef:
                  name: sb-configs
                  key: swagger.api.path
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 250m
          ports:
            - containerPort: 8080
              protocol: TCP
        - name: cloud-sql-proxy
          # image: gcr.io/cloudsql_docker/gce-proxy:latest
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
          imagePullPolicy: Always
          args:
            # 指定資料庫的連線名稱，可以在 Cloud SQL 執行個體資訊頁面中查到
            - lab-project-438121:asia-east1:sb-monitoring-lab
            # - --credentials-file=/secrets/service_account.json
            - --private-ip
            - --debug
            - --debug-logs
            # 指定要將監控相關資訊輸出到哪個 GCP 專案上
            # - --telemetry-project=lab-project
            # 這些監控相關的資訊其名稱須加上什麼前綴字，選填
            # - --telemetry-prefix=cloud-sql-proxy
            # 可以指定監控相關資訊多久採樣一次，選填
            # - --telemetry-sample-rate 10000
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 128Mi
          # volumeMounts:
          #   - name: service-account-secret
          #     mountPath: /secrets/
          #     readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - SYS_ADMIN
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-monitoring-lab
  namespace: monitoring-labs
spec:
  type: ClusterIP
  selector:
    app: spring-boot-monitoring-lab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
